name: Main
on:  
  push:
    branches: 
      - main
      - production
  pull_request:
      branches:
        - main
        - production
  workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
      - name: Use Node.js
        uses: actions/checkout@v2
            
      - name: Use Node.js step2
        uses: actions/setup-node@v2
      
        with: 
          node.version: "14.x"
      - name: Installacja dependencji
        run: npm install
        
      - name: Uruchomienie testów
        run: npm test
        
  deploy:
     runs-on: ubuntu-latest 
     needs: [build]
     steps: 
      - name: check-out
        uses: actions/checkout@v2
      - name: app service
        uses: azure/appservice-build@v3
        with:
          platform: nodejs
          platform-version: 14.21.3
#             source-directory: <SOURCE_DIR>
#             output-directory: <OUTPUT_DIR>   
      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: mateusz2
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
        
